[project]
name = "rotorch"
version = "0.0.1"
dependencies = ["torch", "kingdon", "einops"]

[project.optional-dependencies]
docs = ["sphinx", "furo", "myst-parser"]
test = ["pytest"]
examples = ["scipy", "e3nn"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]